name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

#concurrency:
#  group: ${{ github.head_ref }}
#  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Rust version
        run: rustc --version
      #      - uses: actions-rs/toolchain@v1
      #        with:
      #          profile: minimal
      #          toolchain: stable
      #          override: true # use selected toolchain for remainder of this step
      #          components: ${{ inputs.components }}
      - name: Initialize cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
