name: Publish
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cd js-sandbox && cargo publish --token ${{ secrets.CRATES_TOKEN }}
